vinylin/orders/urls.py
from django.urls import path

from .views import (
    CartView,
    AddCartItemView,
    RemoveCartItemView,
    MakeOrderView,
    OrderView,
)


urlpatterns = [
    path('cart/<int:cart_pk>/', CartView.as_view(), name='cart'),
    path('cart/<int:cart_pk>/add/<int:product_pk>/',
         AddCartItemView.as_view(),
         name='add_to_cart'),
    path('cart/<int:cart_pk>/remove/<int:order_item_pk>/',
         RemoveCartItemView.as_view(),
         name='remove_from_cart'),

    path('make-order/<int:cart_pk>/',
         MakeOrderView.as_view(),
         name='make_order'),
    path('', OrderView.as_view(), name='orders'),
]

vinylin/users/urls.py
from django.urls import path

from .views import (
    SignInView,
    SignOutView,
    RegisterView,
    SignExceptionsView,
    ProfileView,
    EmailVerificationView,
    EmailChangeView,
    EmailConfirmView,
    PasswordChangeView,
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordChangeCompleteView,
    PasswordResetCompleteView,
)


urlpatterns = [
    path('sign-in/', SignInView.as_view(), name='sign_in'),
    path('sign-out/', SignOutView.as_view(), name='sign_out'),
    path('register/', RegisterView.as_view(), name='register'),
    path('<int:pk>/', ProfileView.as_view(), name='profile'),
    path('sign-exceptions/',
         SignExceptionsView.as_view(),
         name='sign_exceptions'),

    path('email-verification/',
         EmailVerificationView.as_view(),
         name='email_verification'),
    path('email-confirm/<str:token>/',
         EmailConfirmView.as_view(),
         name='email_confirm'),
    path('email-change/',
         EmailChangeView.as_view(),
         name='email_change'),

    path('password-change/',
         PasswordChangeView.as_view(),
         name='password_change'),
    path('password-reset/',
         PasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('password-alert/',
         PasswordChangeCompleteView.as_view(),
         name='password_alert'),
]

vinylin/vinylin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('users/', include('users.urls')),
    path('vinyl/', include('vinyl.urls')),
    path('orders/', include('orders.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

vinylin/orders/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse

from .managers import OrderItemManager
from store.models import Product
from users.models import User


class Cart(models.Model):
    user = models.OneToOneField(to=User, on_delete=models.CASCADE)
    is_reserved = models.BooleanField(default=False)

    def __str__(self):
        return f'({self.pk}) {self.user} Cart'

    def get_absolute_url(self):
        return reverse('cart', kwargs={'cart_pk': self.pk})


@receiver(post_save, sender=User)
def create_cart(sender, instance, created, **kwargs):
    """Creates cart object after user registration"""
    if created:
        Cart.objects.create(user=instance)


class Order(models.Model):
    STATUS_CHOICES = [
        ('NPA', 'not_paid'),
        ('PA', 'is_paid'),
        ('ODE', 'on_delivery'),
        ('DE', 'is_delivered'),
        ('CA', 'canceled'),
    ]

    user = models.ForeignKey(to=User, null=True, on_delete=models.SET_NULL)
    status = models.CharField(max_length=5, choices=STATUS_CHOICES)
    total_price = models.DecimalField(max_digits=7, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'({self.pk}) {self.user} Order'


class OrderItem(models.Model):
    cart = models.ForeignKey(
        to=Cart,
        null=True,
        on_delete=models.SET_NULL,
        related_name='order_items'
    )
    order = models.ForeignKey(
        to=Order,
        null=True,
        on_delete=models.CASCADE,
        related_name='order_items'
    )
    product = models.ForeignKey(
        to=Product,
        null=True,
        on_delete=models.SET_NULL,
    )
    quantity = models.SmallIntegerField(default=1)

    objects = OrderItemManager()

vinylin/users/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField

from users.managers import UserManager
from users.validators import birthday_validator
from vinyl.models import Country


class User(AbstractUser):
    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'

    username = None
    email = models.EmailField(unique=True)
    is_email_verified = models.BooleanField(default=False)

    objects = UserManager()

    def __str__(self):
        return f'({self.pk}) {self.email}'

    def get_absolute_url(self):
        return reverse('profile', kwargs={'pk': self.pk})


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = PhoneNumberField(blank=True, null=True)
    birthday = models.DateField(
        blank=True,
        null=True,
        validators=[birthday_validator]
    )
    country = models.ForeignKey(
        Country,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='countries'
    )
    balance = models.DecimalField(default=0, max_digits=6, decimal_places=2)

    def __str__(self):
        return f'{self.user} ({self.pk})'

    def clean(self):
        if float(self.balance) < 0.00:
            raise ValidationError(
                _('You have not enough balance')
            )

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)

    @property
    def age(self):
        if not self.birthday:
            return None

        current_date = datetime.today().date()
        return int((current_date - self.birthday).days / 365.2425)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

vinylin/users/forms.py
from django import forms
from django.contrib.auth import password_validation, get_user_model
from django.contrib.auth import forms as auth_forms
from django.core.validators import MinValueValidator
from django.utils.translation import gettext_lazy as _
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberInternationalFallbackWidget

from .models import Profile
from vinyl.models import Country


UserModel = get_user_model()


class SignInForm(auth_forms.AuthenticationForm):
    username = forms.CharField(
        label='Email',
        widget=forms.EmailInput(attrs={
            'autofocus': True,
            'class': 'input-default',
            'placeholder': 'email'
        })
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'current-password',
            'class': 'input-default',
            'placeholder': 'password',
        })
    )


class UserForm(auth_forms.UserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'class': 'input-default',
            'placeholder': 'password',
        }),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'class': 'input-default',
            'placeholder': 'password',
        }),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )
    phone = PhoneNumberField(
        required=False,
        widget=PhoneNumberInternationalFallbackWidget(attrs={
            'class': 'input-default',
            'placeholder': 'phone',
        })
    )
    birthday = forms.DateField(
        required=False,
        label=_('Birthday'),
        widget=forms.TextInput(
            attrs={'type': 'date', 'class': 'input-default'}
        )
    )
    country = forms.ModelChoiceField(
        queryset=Country.objects.all(),
        required=False,
    )

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get("password1"))

        if commit:
            user.save()
            if not self._is_profile_blank():
                profile = Profile.objects.get(user=user.pk)
                self._save_profile(profile=profile)
        return user

    def _is_profile_blank(self):
        for field in ('phone', 'birthday', 'country'):
            if field in self.changed_data:
                return False
        return True

    def _get_profile_data(self):
        phone = self.cleaned_data.get('phone')

        profile_data = {
            'phone': phone,
            'birthday': self.cleaned_data.get('birthday'),
            'country': self.cleaned_data.get('country'),
        }
        return profile_data

    def _save_profile(self, profile: Profile):
        profile_data = self._get_profile_data()
        profile.phone = profile_data.get('phone')
        profile.birthday = profile_data.get('birthday')
        profile.country_id = profile_data.get('country')

        profile.save()
        return profile

    class Meta:
        model = UserModel
        fields = ('email', 'first_name', 'last_name')
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'input-default',
                'placeholder': 'username'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'input-default',
                'placeholder': '@mail'}),
            'first_name': forms.TextInput(attrs={
                'class': 'input-default',
                'placeholder': 'first name'
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'input-default',
                'placeholder': 'last name'
            }),
        }


class TokenForm(forms.Form):
    code = forms.CharField(
        label='Your code:',
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'input-default',
            'placeholder': 'past your code here ...'
        })
    )


class EmailForm(forms.Form):
    new_email = forms.EmailField(
        label='New e-mail address:',
        widget=forms.EmailInput(attrs={
            'class': 'input-default',
            'placeholder': 'enter your new e-mail ...'
        })
    )


class AddBalanceAdminForm(forms.Form):
    balance = forms.IntegerField(
        label=_('Balance will increase by this number'),
        widget=forms.NumberInput(),
        validators=[MinValueValidator(0)]
    )

vinylin/orders/views.py
from django.core.exceptions import ValidationError
from django.db import transaction
from django.db.models import F, DecimalField, Sum
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView
from django.shortcuts import redirect, render

from .emails import AddCartItemEmailMessage, OrderEmailMessage
from .forms import OrderItemQuantityForm
from .models import OrderItem, Order
from .mixins import UserOrdersPermissionMixin
from store.models import Storage


class CartView(UserOrdersPermissionMixin, ListView):
    template_name = 'orders/cart.html'
    context_object_name = 'cart_items'

    def get_queryset(self):
        return (
            OrderItem.objects.filter(cart_id=self.kwargs.get('cart_pk'))
                             .order_by('product_id')
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_pk'] = self.kwargs.get('cart_pk')
        context['total_price'] = count_total_price(self.get_queryset())
        return context

    def post(self, request, *args, **kwargs):
        """Used to change the quantity of order items in the cart"""
        order_item_id = request.POST['order_item_id']
        order_item_obj = OrderItem.objects.get(pk=order_item_id)
        form = OrderItemQuantityForm(
            data=request.POST,
            instance=order_item_obj
        )

        if not form.is_valid():
            return redirect('cart', cart_pk=request.user.cart.pk)

        form.save()
        return redirect('cart', cart_pk=request.user.cart.pk)


class AddCartItemView(UserOrdersPermissionMixin, CreateView):
    model = OrderItem

    def get(self, request, *args, **kwargs):
        return self._add_to_cart(request, *args, **kwargs)

    @staticmethod
    def _add_to_cart(request, *args, **kwargs):
        cart_pk = kwargs.get('cart_pk')
        product_pk = kwargs.get('product_pk')

        order_item, created_order_item = OrderItem.objects.get_or_create(
            cart_id=cart_pk,
            order=None,
            product_id=product_pk,
        )
        if not created_order_item:
            order_item.quantity = F('quantity') + 1
            order_item.save()

        # if request.user.is_email_verified:
        # self._mail_order_item(request, {'item': order_item})
        return redirect('cart', cart_pk=cart_pk)

    @staticmethod
    def _mail_order_item(request, context):
        message = AddCartItemEmailMessage(request, context)
        return message.send(fail_silently=True)


class RemoveCartItemView(UserOrdersPermissionMixin, UpdateView):
    model = OrderItem

    def get(self, request, *args, **kwargs):
        order_item_pk = kwargs.get('order_item_pk')
        cart_pk = kwargs.get('cart_pk')
        OrderItem.objects.filter(pk=order_item_pk).delete()
        return redirect('cart', cart_pk=cart_pk)


class OrderView(ListView):
    template_name = 'orders/orders.html'
    context_object_name = 'orders'

    def get_queryset(self):
        return (
            Order.objects.filter(user=self.request.user)
                         .prefetch_related('order_items')
        )


class MakeOrderView(UserOrdersPermissionMixin, CreateView):
    def get(self, request, *args, **kwargs):
        return self._make_order(request, kwargs.get('cart_pk'))

    @transaction.atomic
    def _make_order(self, request, cart_pk):
        order_items = OrderItem.objects.filter(cart_id=cart_pk)
        total_price = count_total_price(order_items)

        discard_balance = self._discard_user_balance(request, total_price)
        if not discard_balance:
            return self._alert_user(request, cart_pk)

        self._update_storage(order_items)
        new_order = Order.objects.create(
            user=request.user,
            status='PA',
            total_price=total_price,
        )
        order_items.update(order=new_order, cart=None)

        context = {
            'order_items': OrderItem.objects.filter(order=new_order),
            'total_price': total_price,
        }
        self._mail_order(request, context)
        return redirect('orders')

    @staticmethod
    def _discard_user_balance(request, total_price):
        try:
            user_profile = request.user.profile
            new_user_balance = float(user_profile.balance) - float(total_price)

            decimal = DecimalField(max_digits=6, decimal_places=2)
            new_user_balance = str(round(new_user_balance, 2))
            new_user_balance = decimal.clean(new_user_balance,
                                             model_instance=None)
            user_profile.balance = new_user_balance
            user_profile.save()
            return user_profile

        except ValidationError:
            return None

    @staticmethod
    def _alert_user(request, cart_pk):
        context = {
            'alert_message': 'You have not enough balance to make this order',
            'redirect_url': reverse_lazy('cart',
                                         kwargs={'cart_pk': cart_pk})
        }
        return render(request, 'alert.html', context)

    @staticmethod
    def _update_storage(queryset):
        """Updates the quantity of products in the storage"""
        storages = []
        for item in queryset.select_related('product__storage'):
            storage = item.product.storage
            storage.quantity = F('quantity') - item.quantity
            storages.append(storage)

        return Storage.objects.bulk_update(storages, ['quantity'])

    @staticmethod
    def _mail_order(request, context):
        message = OrderEmailMessage(request, context)
        return message.send(fail_silently=True)


def count_total_price(queryset):
    if not queryset.exists():
        return None
    return round(queryset.aggregate(Sum('final_price'))['final_price__sum'], 2)

vinylin/orders/templates/orders/cart_item_quantity.html
<form class="cart-quantity-form"
      method="post" action="{% url 'cart' cart_pk=cart_pk %}"
      onchange="sendForm(this);">
  {% csrf_token %}
  {{ form }}
  <input type="hidden" name="order_item_id" value="{{ order_item_id }}">

  <script>
      function sendForm(e) {
          e.submit();
      }
  </script>
</form>

vinylin/orders/templates/orders/css_email.html
{% load static %}

<style>
  * {
      font-weight: inherit;
      font-family: inherit;
      font-style: inherit;
      font-size: 100%;
      border: 0 none;
      padding: 0;
      margin: 0;
  }

  body {
      font-family: 'PTSans-Regular', sans-serif;
      background-color: white;
      position: relative;
      overflow-x: hidden;
      opacity: 1;
  }

  a {
      color: inherit;
      text-decoration: none;
  }

  a:visited {
      color: black;
  }

  img {
      width: 100%;
  }

  h1 {
      display: block;
      font-size: inherit;
      margin-block-start: 0;
      margin-block-end: 0;
      margin-inline-start: 0;
      margin-inline-end: 0;
      font-weight: 0;
  }

  header {
      position: relative;
      margin: 24px 0 14px 0;
  }

  li {
      list-style-type: none;
  }

  .container {
      margin: 0 200px;
  }

  li.signed-li > a {
      font-size: 22px;
      color: white;
  }

  .button-wrapper-sign {
      background-color: black;
      color: white;
      border-radius: 10px;
      width: 115px;
      height: 32px;
      text-align: center;
      cursor: pointer;
      padding-bottom: 2px;
  }

  .button-wrapper-sign > a {
      color: white;
      font-size: 22px;
  }

  ul.profile-buttons {
      width: 300px;
      margin: 30px auto;
  }

  .button-wrapper {
      background-color: black;
      color: white;
      border-radius: 10px;
      width: 300px;
      height: 32px;
      text-align: center;
      cursor: pointer;
      padding-bottom: 3px;
  }

  li.profile-button {
      margin-bottom: 20px;
  }

  .button-wrapper > a {
      color: white;
      font-size: 25px;
  }

  .red-button-wrapper {
      background-color: darkred !important;
  }

  .button1 {
      font-size: 22px;
      background-color: black;
      color: white;
      border-radius: 10px;
      width: 100px;
      height: 35px;
      text-align: center;
  }

  #id_password {
      margin-bottom: 1px;
  }

  .try-later {
      width: 100px;
      margin-top: 40px;
      font-size: 20px;
  }

  a.password-reset-a {
      text-decoration: underline;
      margin-bottom: 50px;
  }

  span.user-greetings {
      font-size: 22px;
      text-align: center;
  }

  form.sign-form {
      display: flex;
      flex-direction: column;
      align-items: center;
  }

  input.input-default {
      border: 3px solid black;
      border-radius: 5px;
      width: 350px;
      font-size: 22px;
      margin: 0 auto 50px auto;
      padding: 7px 5px;
      text-align: center;
  }

  #id_phone_prefix {
      border: 3px solid black;
      border-radius: 5px;
      width: 350px;
      font-size: 22px;
      margin: 0 auto 50px auto;
      padding: 7px 5px;
      text-align: center;
  }

  #id_country {
      border: 3px solid black;
      border-radius: 5px;
      width: 350px;
      font-size: 22px;
      margin: 0 auto 50px auto;
      padding: 7px 5px;
      text-align: center;
  }

  form.register-form > input {
      margin-bottom: 30px;
  }

  button.sign-in-button, button.register-button {
      cursor: pointer;
  }

  .email-description {
      text-align: center;
      font-size: 50px;
      font-weight: bold;
      margin: 40px 0 80px 0;
  }

  a.try-later {
      margin-top: 40px;
  }

  a.email-status {
      color: darkred;
  }

  .email-status-desc {
      display: block;
      width: 159px;
      color: darkred;
      background-color: darkred;
      border-radius: 5px;
      text-align: center;
      position: absolute;
      left: 919px;
      top: 75px;
      height: 14px;
  }

  .email-status-desc > a {
      color: white;
      font-size: 10px;
      position: absolute;
      right: 9px;
  }

  a.email-status:hover .email-status-desc {
      display: block;
  }

  #id_old_password, #id_new_password1, #id_new_password2 {
      border: 3px solid black;
      border-radius: 5px;
      width: 350px;
      font-size: 22px;
      margin: 0 auto 50px auto;
      padding: 7px 5px;
      text-align: center;
  }

  .profile-li {
      font-size: 22px;
  }

  .profile-data {
      font-weight: bold;
      font-size: 25px;
  }

  .profile-name {
      text-align: center;
      font-size: 50px;
      font-weight: bold;
      margin: 40px 0 40px 0;
  }

  #id_email {
      border: 3px solid black;
      border-radius: 5px;
      width: 350px;
      font-size: 22px;
      margin: 0 auto 50px auto;
      padding: 7px 5px;
      text-align: center;
  }

  .mid-button {
      margin: 30px auto;
      width: 150px;
  }

  ul.errorlist {
      margin-bottom: 3px;
  }

  ul.errorlist > li {
      color: white;
      background-color: darkred;
      border-radius: 5px;
      text-align: center;
      font-weight: lighter;
      font-size: 14px;
  }

  a.profile-a > .button-wrapper {
      font-size: 24px;
  }

  @font-face {
      font-family: 'PTSans-Regular';
      src: url("{% static './font/PTSans-Regular.ttf' %}");
      font-weight: normal;
  }

  .small-container {
      margin: 0 100px;
  }

  ul.vinyl-row {
      display: flex;
      flex-direction: row;
      flex-wrap: wrap;
      justify-content: space-evenly;
      max-width: 100%;
  }

  li.vinyl-li {
      width: 300px;
      overflow: scroll;
  }

  .li-container {
      display: flex;
      flex-direction: column;
      flex-wrap: wrap;
      align-items: center;
      text-align: center;
      padding-top: 20px;
      margin-bottom: 35px;
  }

  .vinyl-img-wrapper {
      position: relative;
  }

  img.vinyl-img {
      width: 220px;
      height: 220px;
      box-sizing: content-box;
      border: 4px solid black;
      border-radius: 50%;
      box-shadow: 5px 5px 15px 8px rgba(0,0,0,0.12);
      z-index: 8;
  }

  img.single-vinyl-img {
      width: 300px;
      height: 300px;
      box-shadow: 5px 5px 15px 8px rgba(0,0,0,0.12);
      z-index: 8;
  }

  img.vinyl-center {
      position: absolute;
      width: 65px;
      height: 65px;
      right: 79px;
      top: 85px;
      border: 2px solid white;
      border-radius: 50%;
      z-index: 9;
  }

  .tag-wrapper {
      position: absolute;
      left: 131px;
      bottom: 4px;
      z-index: 11;
      text-align: center;
  }

  .vinyl-index-tag {
      height: 28px;
      width: 94px;
      background-color: rgb(113, 45, 45);
      box-shadow: 5px 5px 15px -4px rgba(0,0,0,0.33);
      border-radius: 10px;
  }

  .vinyl-index-tag > span {
      color: white;
      font-size: 16px;
  }

  span.vinyl-title {
      color: black;
      font-size: 17px;
      font-weight: bold;
      margin-top: 50px;
      z-index: 10;
  }

  .index-button-wrapper {
      width: 220px !important;
      height: 28px !important;
      margin-top: 10px !important;
  }

  .vinyl-index-price {
      font-size: 17px;
      font-weight: bold;
      color: rgb(2, 73, 2);
  }

  a.index-buy-button {
      font-size: 22px !important;
  }

  .single-vinyl {
      display: flex;
      flex-direction: row;
  }

  section.single-vinyl-info {
      margin-left: 50px;
  }

  .single-button-wrapper {
      width: 300px !important;
      height: 50px !important;
      margin-top: 30px;
  }

  .single-button-wrapper:hover {
      background-color: rgb(2, 73, 2);;
  }

  .single-buy-button {
      font-size: 36px;
  }

  .single-buy-button__disabled {
      font-size: 36px;
      cursor: none !important;
  }

  .single-button-wrapper__disabled {
      width: 300px !important;
      height: 50px !important;
      cursor: default !important;
      opacity: 0.3;
      margin-top: 30px;
  }

  ul.single-vinyl-info > li {
      margin-bottom: 10px;
  }

  .vinyl-single-title > h2 {
      font-size: 50px;
      margin-bottom: 10px;
  }

  span.single-info-title {
      font-weight: bold;
      text-decoration: underline;
  }

  ul.single-vinyl-tags-ul {
      display: flex;
      flex-direction: row;
  }

  ul.single-vinyl-tags-ul > li {
      margin-right: 30px;
      text-align: center;
  }

  ul.single-vinyl-genres {
      display: flex;
      flex-direction: row;
  }

  ul.single-vinyl-genres > li {
      padding-left: 6px;
  }

  li.vinyl-single-price {
      font-size: 30px;
      font-weight: bold;
      color: rgb(2, 73, 2);
  }

  .single-prices-wrapper {
      display: flex;
      flex-direction: row;
  }

  span.vinyl-single-price__old-price {
      font-size: 20px;
      font-weight: bold;
      color: rgb(2, 73, 2);
      text-decoration: rgb(2, 73, 2) line-through;
  }

  span.vinyl-single-price__new-price {
      font-size: 30px;
      font-weight: bold;
      color: rgb(150, 15, 15);
      margin-right: 5px;
  }

  span.vinyl-index-price__old-price {
      font-size: 15px;
      font-weight: bold;
      color: rgb(2, 73, 2);
      text-decoration: rgb(2, 73, 2) line-through;
  }

  span.vinyl-index-price__new-price {
      font-size: 17px;
      font-weight: bold;
      color: rgb(150, 15, 15);
  }

  .vinyl-overview > p {
      margin-bottom: 10px;
  }

  section.cart {
      margin-bottom: 80px;
  }

  img.cart-vinyl-img {
      width: 150px;
      height: 150px;
  }

  .cart-title-wrapper {
      text-align: center;
      margin-bottom: 70px;
  }

  h2.cart-title {
      font-size: 45px;
      font-weight: bold;
  }

  ul.cart-item-ul {
      display: flex;
      flex-direction: row;
  }

  ul.cart-ul > li {
      margin-bottom: 0;
  }

  hr.cart-hr {
      opacity: 0.2;
      border-radius: 2px;
      color: black;
      background-color: black;
      height: 1px;
      margin-top: 11px;
      margin-bottom: 15px;
  }

  .cart-item-info {
      margin: auto 10px;
  }

  h3.cart-item-title {
      font-size: 28px;
      font-weight: bold;
  }

  ul.cart-tag-ul > li {
      margin-right: 9px;
  }

  li.cart-tag {
      height: 24px;
  }

  li.cart-tag > span {
      font-size: 14px;
  }

  #id_quantity {
      border: 1px solid black;
      border-radius: 5px;
      width: 44px;
      font-size: 17px;
      text-align: center;
  }

  form.quantity-form {
      margin-left: 30px;
      margin-top: 69px;
  }

  li.cart-item-price {
      float: right;
  }

  li.cart-item-remove-li {
      padding-left: 60px;
  }

  a.remove-item {
      position: absolute;
      font-size: 22px;
  }

  .order-final-wrapper {
      width: 300px;
      margin: 0 auto;
  }

  .total-price-wrapper {
      text-align: center;
  }

  span.total-price-title {
      font-size: 40px;
      font-weight: bold;
  }

  span.total-price-title {
      font-size: 35px;
      font-weight: bold;
  }

  span.total-price {
      font-size: 35px;
      font-weight: bold;
      color: rgb(2, 73, 2);
      text-decoration: underline;
  }

  .user-balance {
      text-align: center;
      margin-top: 17px;
  }

  span.user-balance-title {
      font-weight: bold;
  }

  span.user-balance {
      font-weight: bold;
      color: rgb(2, 73, 2);
      text-decoration: underline;
  }

  .make-order {
      font-size: 36px;
  }

  span.order-number {
      font-size: 25px;
  }

  span.order-item-quantity {
      font-size: 22px;
      margin-left: 25px;
      color: rgb(113, 45, 45);
  }
</style>